//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "player")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub username: String,
    #[sea_orm(unique)]
    pub email: String,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub password_hash: Vec<u8>,
    #[sea_orm(column_type = "Text")]
    pub biography: String,
    pub country: String,
    pub flair: String,
    pub real_name: String,
    pub location: Option<String>,
    pub fide_rating: Option<i32>,
    pub elo_rating: i32,
    pub social_links: Option<Vec<String>>,
    pub is_enabled: bool
}



#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
